name: Demo workflow
on: workflow_dispatch
jobs: 
  print_demo:
    runs-on: windows-latest
    steps:
      - name: Print to console
        run: echo Hello
      - name: Print a few lines
        run: |
          echo First line!
          echo Second line
